name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "28608251-cee7d8c0-e23a-42dc-996d-dca41f6b0a7b" -e "28608251-a2763c79-ac25-4353-b65e-f598ac615ee6"
          postman collection run "28608251-cee7d8c0-e23a-42dc-996d-dca41f6b0a7b" \
            -e "28608251-a2763c79-ac25-4353-b65e-f598ac615ee6" \
            -i "28608251-163c0350-d89e-47cc-a10d-e0d41ebf3021" \
            -i "28608251-42fabfcb-5531-4ec8-83ba-c41f08547239"